import * as THREE from 'three';
import { OrbitControls } from './vendor/OrbitControls.js';
import { GLTFLoader } from './vendor/GLTFLoader.js';
import { RoomEnvironment } from './vendor/RoomEnvironment.js';

const viewport=document.querySelector('#viewport'), loading=document.querySelector('#loading');
const definitions=[['Roof surfaces',/roof|saucer/i],['Domes & lanterns',/dome|lantern/i],['Canopies',/canopy|fascia/i],['Glazing & doors',/glaz|door|mullion|entry frame/i],['Tower & antennas',/mast|antenna|tower|observation/i],['Columns & facades',/column|facade|building|annex|drum/i],['Ground & circulation',/slab|podium|stair|landing|promenade|baluster|handrail|floor/i],['Site details',/.*/]];
let renderer, controls, camera, model, span=100, ready=false, currentView='Perspective';
const scene=new THREE.Scene();scene.background=new THREE.Color('#e4e9ed');
const center=new THREE.Vector3(), size=new THREE.Vector3(), groups=definitions.map(([name,pattern])=>({name,pattern,items:[]}));
const perspective=new THREE.PerspectiveCamera(38,1,.01,10000), ortho=new THREE.OrthographicCamera(-100,100,100,-100,.01,10000);
function resize(){if(!renderer)return;const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h);perspective.aspect=w/h;perspective.updateProjectionMatrix();const extent=span*.67;ortho.left=-extent*w/h;ortho.right=extent*w/h;ortho.top=extent;ortho.bottom=-extent;ortho.updateProjectionMatrix();if(ready)setView(currentView);}
function setView(view){if(!ready||!['Perspective','Top','Front','Back','Left','Right'].includes(view))return false;currentView=view;camera=view==='Perspective'?perspective:ortho;controls.object=camera;controls.target.copy(center);camera.up.set(0,1,0);const directions={Perspective:[1,.75,1.25],Top:[0,1,0],Front:[0,0,1],Back:[0,0,-1],Left:[-1,0,0],Right:[1,0,0]};if(view==='Top')camera.up.set(0,0,-1);const direction=new THREE.Vector3(...directions[view]).normalize();const aspect=viewport.clientWidth/viewport.clientHeight;const radius=size.length()/2;const fov=THREE.MathUtils.degToRad(perspective.fov);const angle=Math.min(fov/2,Math.atan(Math.tan(fov/2)*aspect));const distance=radius/Math.sin(angle)*1.12;camera.position.copy(center).addScaledVector(direction,distance);camera.near=Math.max(span/10000,.001);camera.far=distance+span*12;camera.zoom=1;if(view!=='Perspective'){const width=view==='Left'||view==='Right'?size.z:size.x;const height=view==='Top'?size.z:size.y;const half=Math.max(height,width/aspect)*.61;camera.left=-half*aspect;camera.right=half*aspect;camera.top=half;camera.bottom=-half;}camera.updateProjectionMatrix();camera.lookAt(center);controls.update();document.querySelector('#view-name').textContent=view==='Perspective'?'3D view':view+' view';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));return true;}
function sync(){const items=groups.flatMap(g=>g.items),shown=items.filter(i=>i.object.visible).length;document.querySelector('#count').textContent=`${shown} / ${items.length} visible`;document.querySelector('#selection').textContent=shown===items.length?'All objects visible':`${items.length-shown} objects hidden`;groups.forEach(g=>{if(!g.checkbox)return;const n=g.items.filter(i=>i.object.visible).length;g.checkbox.checked=n===g.items.length;g.checkbox.indeterminate=n>0&&n<g.items.length;g.items.forEach(i=>i.checkbox.checked=i.object.visible)});}
function setGroup(name,visible){const group=groups.find(g=>g.name===name);if(!ready||!group||typeof visible!=='boolean')throw Error('Choose an existing group and a boolean visibility.');group.items.forEach(i=>i.object.visible=visible);sync();return {group:name,visible,count:group.items.length};}
function makeLayers(){const host=document.querySelector('#layers');groups.filter(g=>g.items.length).forEach(g=>{const details=document.createElement('details'),summary=document.createElement('summary'),label=document.createElement('label'),checkbox=document.createElement('input'),number=document.createElement('span'),children=document.createElement('div');checkbox.type='checkbox';checkbox.checked=true;checkbox.setAttribute('aria-label',`Show ${g.name}`);g.checkbox=checkbox;checkbox.addEventListener('change',()=>setGroup(g.name,checkbox.checked));label.addEventListener('click',e=>e.stopPropagation());label.append(checkbox,document.createTextNode(g.name));number.className='number';number.textContent=g.items.length;summary.append(label,number);children.className='children';const repeated=new Map();g.items.forEach(i=>{const row=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.checked=true;const n=(repeated.get(i.name)||0)+1;repeated.set(i.name,n);const total=g.items.filter(x=>x.name===i.name).length;row.append(box,document.createTextNode(i.name+(total>1?` · ${n}`:'')));box.addEventListener('change',()=>{i.object.visible=box.checked;sync()});i.checkbox=box;children.append(row)});details.append(summary,children);host.append(details)});sync();}
async function init(){try{renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;viewport.prepend(renderer.domElement);camera=perspective;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true;controls.addEventListener('start',()=>{document.querySelector('#view-name').textContent='Custom view';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'))});scene.add(new THREE.HemisphereLight(0xffffff,0x82929d,1));const sun=new THREE.DirectionalLight(0xffffff,1.5);sun.position.set(100,150,90);scene.add(sun);const generator=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=generator.fromScene(room,.04).texture;room.dispose();generator.dispose();resize();const gltf=await new GLTFLoader().loadAsync('./bldg.glb',e=>{loading.textContent=e.total?`Loading your building… ${Math.round(e.loaded/e.total*100)}%`:'Loading your building…'});model=gltf.scene;scene.add(model);const bounds=new THREE.Box3().setFromObject(model);bounds.getCenter(center);bounds.getSize(size);span=Math.max(size.x,size.y,size.z);model.traverse(o=>{const nodeIndex=gltf.parser.associations.get(o)?.nodes;if(nodeIndex===undefined)return;const node=gltf.parser.json.nodes[nodeIndex];if(node.mesh===undefined)return;const name=node.name||`Object ${nodeIndex+1}`;const group=groups.find(g=>g.pattern.test(name));group.items.push({name,object:o});});const grid=new THREE.GridHelper(span*1.8,24,0xb1bec7,0xcbd5dc);grid.position.set(center.x,bounds.min.y-.02,center.z);scene.add(grid);ready=true;makeLayers();resize();loading.hidden=true;renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera)});new ResizeObserver(resize).observe(viewport);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();loading.hidden=false;loading.textContent='The 3D view was interrupted. Reload the page to restore it.'});registerTools();}catch(error){console.error(error);loading.hidden=false;loading.textContent='The model could not be opened. Check that WebGL is enabled, then reload this page.';}}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
document.querySelector('#reset').addEventListener('click',()=>setView('Perspective'));
document.querySelector('#show-all').addEventListener('click',()=>{groups.forEach(g=>g.items.forEach(i=>i.object.visible=true));sync()});
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'set_building_camera',description:'Switch the building camera to a named view.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['Perspective','Top','Front','Back','Left','Right']}},required:['view'],additionalProperties:false},execute:({view})=>{if(!setView(view))throw Error('Unknown view or model unavailable.');return {view}}},{name:'set_building_group_visibility',description:'Show or hide an architectural object group.',inputSchema:{type:'object',properties:{group:{type:'string',enum:groups.map(g=>g.name)},visible:{type:'boolean'}},required:['group','visible'],additionalProperties:false},execute:({group,visible})=>setGroup(group,visible)}];for(const tool of tools){try{Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(console.warn)}catch(e){console.warn(e)}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
init();

