import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {KTX2Loader} from 'three/addons/loaders/KTX2Loader.js';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {sunPosition} from './solar.js';
const $=id=>document.getElementById(id), host=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#e8ece5');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;host.appendChild(renderer.domElement);
const pmrem=new THREE.PMREMGenerator(renderer),environment=new RoomEnvironment();scene.environment=pmrem.fromScene(environment,.04).texture;scene.environmentIntensity=.35;environment.dispose();pmrem.dispose();
const camera=new THREE.PerspectiveCamera(42,1,.01,1000),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=Math.PI*.495;
scene.add(new THREE.HemisphereLight(0xe6efff,0x817968,1.5));
const sun=new THREE.DirectionalLight(0xfff2d5,3);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);sun.shadow.normalBias=.015;sun.shadow.bias=-.00008;scene.add(sun,sun.target);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(400,400),new THREE.MeshStandardMaterial({color:0xcdd3bf,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.025;ground.receiveShadow=true;scene.add(ground);
const grid=new THREE.GridHelper(120,60,0x8d9b84,0xb6c0aa);grid.position.y=-.02;scene.add(grid);
const north=new THREE.ArrowHelper(new THREE.Vector3(0,0,-1),new THREE.Vector3(-15,.08,0),10,0x486547,2,1);scene.add(north);
const labelCanvas=document.createElement('canvas');labelCanvas.width=128;labelCanvas.height=128;const ctx=labelCanvas.getContext('2d');ctx.fillStyle='#38563c';ctx.font='bold 70px sans-serif';ctx.textAlign='center';ctx.fillText('N',64,90);const northLabel=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(labelCanvas),depthTest:false}));northLabel.position.set(-15,1,-12);northLabel.scale.set(2,2,2);scene.add(northLabel);
const marker=new THREE.Mesh(new THREE.SphereGeometry(.65),new THREE.MeshBasicMaterial({color:0xd7a449}));scene.add(marker);
let path,model,token=0,meshCount=0;
const draco=new DRACOLoader().setDecoderPath('./vendor/addons/libs/draco/gltf/');
const ktx=new KTX2Loader().setTranscoderPath('./vendor/addons/libs/basis/').detectSupport(renderer);
const loader=new GLTFLoader().setDRACOLoader(draco).setKTX2Loader(ktx).setMeshoptDecoder(MeshoptDecoder);
function dispose(root){const geometries=new Set(),materials=new Set(),textures=new Set();root.traverse(o=>{if(o.geometry)geometries.add(o.geometry);for(const m of [].concat(o.material||[])){materials.add(m);for(const v of Object.values(m))if(v?.isTexture)textures.add(v);}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());}
function fit(){if(!model)return;const sphere=new THREE.Box3().setFromObject(model,true).getBoundingSphere(new THREE.Sphere());const angle=Math.min(THREE.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*camera.aspect));const distance=sphere.radius/Math.sin(angle)*1.15;controls.target.copy(sphere.center);camera.position.copy(sphere.center).add(new THREE.Vector3(1,.7,1).normalize().multiplyScalar(distance));camera.far=Math.max(1000,distance*10);camera.updateProjectionMatrix();controls.maxDistance=distance*8;controls.update();}
async function load(source,name){const current=++token;$('status').textContent='Loading '+name+'…';try{const gltf=typeof source==='string'?await loader.loadAsync(source):await loader.parseAsync(source,'');if(current!==token){dispose(gltf.scene);return;}const root=gltf.scene;root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(root,true),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const extent=Math.max(size.x,size.y,size.z);if(!Number.isFinite(extent)||extent<=0)throw Error('No visible geometry found.');meshCount=0;root.traverse(o=>{if(o.isLight)o.visible=false;if(o.isMesh){meshCount++;o.castShadow=o.receiveShadow=true;for(const material of [].concat(o.material)){material.side=THREE.DoubleSide;material.shadowSide=THREE.DoubleSide;material.needsUpdate=true;}}});if(!meshCount)throw Error('No meshes found.');const scale=20/extent;const offset=new THREE.Group();offset.add(root);offset.position.set(-center.x,-bounds.min.y,-center.z);const wrapper=new THREE.Group();wrapper.scale.setScalar(scale);wrapper.add(offset);if(model){scene.remove(model);dispose(model);}model=wrapper;scene.add(model);orient();fit();$('modelName').textContent=name;$('modelInfo').textContent=meshCount+' meshes · fitted proportionally · Y up';$('status').textContent='';window.viewerReady=true;}catch(e){$('status').textContent='Could not load model: '+e.message;console.error(e);}}
function orient(){if(model)model.rotation.y=-THREE.MathUtils.degToRad(+$('north').value);$('bearing').textContent=$('north').value+'°';}
function direction(p){return new THREE.Vector3(Math.cos(p.altitude)*Math.sin(p.azimuth),Math.sin(p.altitude),-Math.cos(p.altitude)*Math.cos(p.azimuth));}
function updateSun(){if(!$('date').value)return;const minutes=+$('time').value,p=sunPosition($('date').value,minutes);sun.position.copy(direction(p).multiplyScalar(120));sun.target.position.set(0,0,0);sun.intensity=p.altitude>0?3:0;marker.position.copy(direction(p).multiplyScalar(45));marker.visible=p.altitude>0;const c=sun.shadow.camera;Object.assign(c,{left:-70,right:70,top:70,bottom:-70,near:1,far:250});c.updateProjectionMatrix();$('clock').textContent=p.date.toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'});$('zone').textContent=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',timeZoneName:'short'}).formatToParts(p.date).find(p=>p.type==='timeZoneName').value;$('altitude').textContent=THREE.MathUtils.radToDeg(p.altitude).toFixed(1)+'°';$('azimuth').textContent=THREE.MathUtils.radToDeg(p.azimuth).toFixed(1)+'°';$('sunState').textContent=p.altitude>0?'Azimuth clockwise from true north.':'Sun below horizon · direct sunlight is off.';if(path){scene.remove(path);path.geometry.dispose();path.material.dispose();}const points=[];for(let t=0;t<=1440;t+=5){const s=sunPosition($('date').value,t);if(s.altitude>=0)points.push(direction(s).multiplyScalar(45));}path=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xbba165,transparent:true,opacity:.65}));path.visible=$('path').checked;scene.add(path);}
$('time').oninput=updateSun;$('date').onchange=()=>{document.querySelectorAll('[data-date]').forEach(b=>b.classList.toggle('active',$('date').value==='2026-'+b.dataset.date));updateSun();};document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{$('date').value='2026-'+b.dataset.date;$('date').onchange();});$('north').oninput=orient;$('fit').onclick=fit;$('path').onchange=()=>path.visible=$('path').checked;$('grid').onchange=()=>grid.visible=$('grid').checked;
async function file(f){if(!f)return;if(!f.name.toLowerCase().endsWith('.glb')){$('status').textContent='Please choose a self-contained .glb file.';return;}await load(await f.arrayBuffer(),f.name);}
$('file').onchange=e=>{file(e.target.files[0]);e.target.value='';};window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>{e.preventDefault();file(e.dataTransfer.files[0]);});new ResizeObserver(()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);}).observe(host);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});updateSun();load('./assets/bldg%20(1).glb','bldg (1).glb');
